export const CHANGE_USER_INPUT="text changed success";
export const SET_SUGGESTIONS="suggestions changed success";
export const SET_CURR_PICK="current pick setted";
export const SET_CURR_WEATHER="current weather setted";
export const ERROR="error over here !!!"
export const SET_WEEKLY_WEATHER="weekly weather setted";
export const CHANGE_COLOR_THEME="app theme black/white changed success"
export const CHANGE_WEATHER_TYPE="app weather type c/f changed success"
export const UPDATE_FAVORITES="favorites was updated success"